# -*- coding: utf-8 -*-
"""Lossesipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qw2bd7C-o_sfeCSI29UWsxLvuSBS_Dev

# MSE (Mean Sqaured Error) 

<img src = "https://ambrapaliaidata.blob.core.windows.net/ai-storage/articles/2.png">

Mean Squared Error (MSE) is a common metric used to measure the performance of regression models. It measures the average squared difference between the predicted and actual values of a given dataset.

To calculate the MSE, you need to take the difference between the predicted and actual values for each data point in the dataset, square the difference, and then take the average of all these squared differences. This provides an overall measure of how well the model is performing in terms of predicting the target variable.

MSE is a useful metric because it penalizes large errors more heavily than small errors, since the errors are squared. This means that a model with a high MSE is likely making larger errors on average than a model with a lower MSE.

However, MSE is sensitive to outliers in the data, as they can have a large impact on the overall score. In cases where outliers are a concern, other metrics such as Mean Absolute Error (MAE) may be more appropriate.

$$Error = \frac {1}{n}\sum\limits_{i = 1}^{n}(actual - predicted)^2$$
"""

import numpy as np

"""Lets assume we have these values"""

predicted = 12
actual = 10

"""The error, also can be said as the difference between these values will be """

predicted - actual

"""Now lets assume we have a list of values"""

predicted = np.array([x for x in range(10)])
actual = np.array([x for x in range(0 , 20 , 2)])

predicted

actual

"""The error for this will be """

error = actual - predicted

error

"""If we calculate the mean of this error, it will be """

error.mean()

"""It can be then said as `mean error`

But as we move to a real world dataset, it is quite possible that these values start to cancel out each other

Thats we introduce a `square` to all the terms, to make them posiitve and still get the results
"""

error = (actual - predicted) ** 2

error

"""And now the mean will be """

error.mean()

"""Though the mean is high, but it would be less vulnerable

Lets now just make a function for this and put all of this seperately
"""

def MSE(predicted , actual):
    
    error = ((predicted - actual) ** 2).mean()

    return error